version: '3.5'

services:
  jekyll:
    image: jekyll/jekyll:3
    command: jekyll serve --watch --force_polling --host 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll
    environment:
      - JEKYLL_ENV=development
